services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  B13\Slugr\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'
  B13\Slugr\Command\RegeneratePageSlugCommand:
    tags:
      -
        name: console.command
        command: 'urls:regenerate'
        description: 'Regenerates page slugs for a specific site, or language, if it changes from the current one'
        schedulable: false
